# Default values for accounts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eureka-deployment
serviceName: eureka
appLabel: eureka
appName: eureka

replicaCount: 1

image:
  repository: shdowblack/eureka
  tag: latest

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resourceserver_enabled: true
otel_enabled: false
kafka_enabled: false